language: java
install: mvn -X clean test install
sudo: true
deploy:
  provider: cloudfoundry
  api: https://api.run.pivotal.io
  username: venke80@gmail.com
  password: Techgig1!
  organization: techgig
  space: development
  
